// pm2 process config — generated by agent during aura-app deploy
// Agent detects pm2 via `which pm2` before using this file
module.exports = {
    apps: [{
        name:   'posh-pusher',
        script: './server.js',
        cwd:    __dirname,
        watch:  false,
        // env populated by agent from .env during deploy
        env: {
            NODE_ENV: 'production',
            PORT:     '3456',
        },
    }],
}
