#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
AURA_PULSE_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
REPO_ROOT=$(CDPATH= cd -- "$AURA_PULSE_ROOT/.." && pwd)

export OPENCLAW_IMAGE="${OPENCLAW_IMAGE:-ghcr.io/openclaw/openclaw:2026.3.24}"
export OPENCLAW_CONFIG_DIR="${OPENCLAW_CONFIG_DIR:-$AURA_PULSE_ROOT/.openclaw-docker/config}"
export OPENCLAW_WORKSPACE_DIR="${OPENCLAW_WORKSPACE_DIR:-$AURA_PULSE_ROOT/.openclaw-docker/workspace}"
export OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-28789}"
export OPENCLAW_PULSE_WS_PORT="${OPENCLAW_PULSE_WS_PORT:-28790}"
export OPENCLAW_PULSE_UI_PORT="${OPENCLAW_PULSE_UI_PORT:-4175}"
export AURA_REPO_DIR="${AURA_REPO_DIR:-$REPO_ROOT}"

mkdir -p "$OPENCLAW_CONFIG_DIR" "$OPENCLAW_WORKSPACE_DIR"